<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>lib.github.joelgodofwar</groupId>
		<artifactId>ShulkerRespawnerLib-parent</artifactId>
		<version>0.2.2-SNAPSHOT</version>
	</parent>

	<artifactId>ShulkerRespawnerLib-MC_26_1_R1</artifactId>

	<repositories>
		<repository>
			<id>papermc</id>
			<url>https://repo.papermc.io/repository/maven-public/</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>io.papermc.paper</groupId>
			<artifactId>paper-api</artifactId>
			<version>26.1.2.build.69-stable</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>lib.github.joelgodofwar</groupId>
			<artifactId>ShulkerRespawnerLib-abstraction</artifactId>
			<version>${project.parent.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>25</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>